### ISSUE TITLE
[ENHANCEMENT] Improvements in the interface of package updates

### ISSUE THREAD

**Issue by Mideks** [marticliment/UniGetUI#1218]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Using this application for the first time, I would like to share the following things that I found unfinished:
1. When a package is updated, it is not removed from the list of packages ready to be updated. This is not inconvenient if only a few packages are selected for upgrade. 
2. For some reason it is possible to put the same package on update/uninstall several times, which is a bit confusing. 
3. The list of available applications lacks any indication that the application right now is in the update queue and its status. (number in queue, or update progress) 
4. When selecting to update some apps, I expected that the order of selection would affect the order in which they were updated. However, this turned out not to be the case 
5. Also, if there are updates, the app will send a notification that there are updates every 15 minutes. This is a bit annoying. I would like to be able to not just turn off notifications of available updates, but to be able to make them less frequent.
6. In the download stage of the new version of the app, there is no indication of how much is downloaded in % and in megabytes

### Describe how this improvement could help users.

I think these changes could improve the usability of the app for updating other programs

**Comment by ppvnf** [comment]
I also think item 2 is confusing

**Comment by BartmanAbyss** [comment]
+1 for the missing download progress indicator

**Comment by kmvan** [comment]
The progress bar...
![image](https://github.com/marticliment/WingetUI/assets/3839554/4a8b7b22-5c5d-4d59-b01d-a5f0d6481186)

**Comment by redactedscribe** [comment]
My first impressions found that this UI...:

- **Lacks any mention of how many packages have been currently selected**. We see "Available updates: ##", but not "Selected packages: ##" or similar. This is useful because if for example an update fails, it remains selected. If you go ahead and later selected a different package and initiate updating without remembering to deselect the package which failed to update, it will attempt to update both again. Seeing a number for selected packages would help.
- **Has all packages selected by default**, which may be more convenient for the person who likes to manually update everything in one go, but as someone who prefers to update a couple apps at a time, I have to deselect everything first (via the button). This isn't much of a problem I guess if you keep the app running (only need to deselect once per session). I still think having everything selected by default isn't ideal, or even needed with options like "Update all" via the system tray (perhaps such a button should be on the program's UI too?). This could be a preferences option to have all or none pre-selected.
- **Doesn't support middle-mouse clicking to scroll**. The middle mouse button appears to act like the left mouse button (double-clicking on an update begins installation). Same for all the UI's tabs.
- **Doesn't bring enough attention to the main Update selected packages button**. Minor, but it could be green, like the GitHub comment button on these issue pages (and red for uninstall equivalent on the Installed Packages tab).

**Comment by marticliment** [comment]
Most of the proposals here have either been fixed or aren't applicable anymore. The rest of them have specific issues opened, so I am going to close this issue
