### ISSUE TITLE
[BUG] Issues with shown packages (malfunctionning source filtering?)

### ISSUE THREAD

**Issue by dcog989** [marticliment/UniGetUI#1844]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

On start-up 'Installed Packages' is displaying only PIP packages even though Winget + Local are selected as well. 

![wingetui 1](https://github.com/marticliment/WingetUI/assets/89043002/790fd461-ee40-444c-8d12-e76d5586bd90)

If I then deselect Local, Winget packages are also displayed:

![wingetui 2](https://github.com/marticliment/WingetUI/assets/89043002/a1607f60-234b-4b13-8edf-07fcf2d66609)

I can then select Local to see all three:

![wingetui 3](https://github.com/marticliment/WingetUI/assets/89043002/2cb4d9bf-4c25-4c17-9681-6b901ab2e364)

I tried resetting Settings but problem persists. Customised Settings:

[WingetUI Settings.json](https://github.com/marticliment/WingetUI/files/14468684/WingetUI.Settings.json)

### WingetUI Log

```text
[WingetUI Log.txt](https://github.com/marticliment/WingetUI/files/14468695/WingetUI.Log.txt)
```

### Package Managers Logs

```text
[WingetUI Package Managers.txt](https://github.com/marticliment/WingetUI/files/14468696/WingetUI.Package.Managers.txt)
```

**Comment by DrStrange** [comment]
I have the same issue, although it seems to me caused by the `Filters` dropdown rather than the `Sources` dropdown. 
What happens is that 3.0-beta0 opens with at the `Discover Packages` tab. The `Filters` dropdown is already open and it shows these selections:
`Package Name`
`Package ID`
`Both`
`Show Similar Packages`
`Exact Match`
None of these are pre-selected. If I go to the `Installed Packages` tab the `Filters` dropdown closes and only Pip and PSWindowsUpdate packages are showing. I then have to open the `Filters` dropdown. The `Show Similar Packages` and `Exact Match` options have disappeared. None of the other three options are pre-selected, which seems to be the problem. I have to click on `Package Name` or `Package ID` or `Both` to get all my packages to show.  
Marti, can you change WingetUI's behaviour so that one of these three options is already pre-selected?

**Comment by dcog989** [comment]
> ...for me it seems to me caused by the `Filters` dropdown ...

Can confirm that selecting a Search mode in Filters causes all packages to be displayed as expected.

Switching any source off / on also works for me.

**Comment by RonnyTNL** [comment]
@marticliment 
Confirm as having the same issue on this end

**Comment by DrStrange** [comment]
With the release of 3.0.0.-beta1 three days ago, I no longer have this issue. All my packages appear when I select the `Installed Packages` tab. When I open the `Filters` tab, under `Search mode` I see that `Both` has been pre-selected.

**Comment by marticliment** [comment]
I am still able to reproduce the issue, so I will maintain this issue open
