### ISSUE TITLE
[BUG] Microsoft .NET SDK 6.0 Update Continuously Offered as an Update

### ISSUE THREAD

**Issue by pwcrickman** [marticliment/UniGetUI#2547]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1-beta2

### Windows version, edition, and architecture

Windows 11 Home 23H2

### Describe your issue

I have both Microsoft .NET SDK 6.0.321 and 6.0.424 installed on my system.  UniGetUI continues to list the update to 6.0.424 for this application in the Software Updates section.  These SDK versions can reside side-by-side.

### Steps to reproduce the issue

Install both SDKs and open UniGetUI and perform the Software Updates refresh.

### UniGetUI Log

```text
Not Needed
```

### Package Managers Logs

```text
Not Needed
```

**Comment by ttom34** [comment]
This issue will be the same on my system.
The Version 6.0.424 is been upgraded, but it will allways show that as upgrade.
I have successfully fixed this for me, with adding the parameter `--uninstall-previous` to winget.
So this may an option for unigetui to implement this parameter at executing winget upgrade.
At least both dot-net SDK 5 and 6 works with this, I think that the installation itself are not testing if its multiple times installed (?).

What not work with this, is the installation of VC-Redistributable 2005 if it was multiple times installed, the only way is to uninstall by hand all older versions to fix.
It can be done maybe with a check for older versions and an automated uninstall before install, since it doesn't work with the winget-parameter itself.

Another point will be, that in the listing also upgrades will be shown with empty versionnumber (DeepL in my case) while the parameter `--include-unknown` is set to winget, so it will be allways listed, even if it is allready upgraded.
For this, an optional setting to exclude this parameter will be much helpfully, instead of setting it to the ignorelist.

**Comment by marticliment** [comment]
Hello,

WinGet (one of the package managers used to provide updates) sometimes fails to detect certain software. Please do use the option "Skip this version" (on the package's context menu) in order to circumvent this issue.

**Comment by ttom34** [comment]
Hello Marti,

Winget itself detect the software and also the different versions, as you can see on this sample (the same as in installed Apps):
![unigetui_sc2](https://github.com/user-attachments/assets/5681b69a-1ffc-4d63-bb7f-a1ffc2ee25da)

On DeepL there is no version number provided, so winget can't check this (for this you can use your suggestion)
![unigetui_sc4](https://github.com/user-attachments/assets/731c8b92-d48b-4222-be1f-87db1090e471)

You should remember that updates to installs not only hold new features and changes, it also fixes exploits (like in Dot Net 5 and 6). If you leaf that outdated and exploitable piece of software as it is (even if a newer one is installed), it can be a security risk on that system, because it can be used by hackers (there are some tools that detect such vulnerabilities). So ignore that is not a good idea I think and the solution with the optional parameter `--uninstall-previous` is simple to be implemented.

**Comment by mika76** [comment]
This is happening with .net sdk 8 too - will try uninstall previous...
